# @package _group_

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-test
  #query_special_suffix: '?'

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
#  file: data.retriever.qas.nq-train
  file: ../../../data/nq-train.tsv

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test

webq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ../../../data/webquestions-train.tsv

webq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ../../../data/webquestions-dev.tsv

squad1_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ../../../data/squad1-train.tsv

squad1_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ../../../data/squad1-dev.tsv

curatedtrec_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ../../../data/curatedtrec-train.tsv

curatedtrec_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ../../../data/curatedtrec-dev.tsv

curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test

